# Generated by Django 6.0.6 on 2026-09-03 12:02

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0008_paiementavancesalaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaire',
            options={'ordering': ['-date_paiement', '-created_at'], 'verbose_name': 'Salaire', 'verbose_name_plural': 'Salaires'},
        ),
        migrations.AddField(
            model_name='salaire',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='salaire',
            name='nombre_jours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salaire',
            name='salaire_contractuel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salaire',
            name='trop_percu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='paiementavancesalaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
