# Generated by Django 6.0.6 on 2026-09-03 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0009_alter_salaire_options_salaire_date_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
