# Generated by Django 6.0.6 on 2026-07-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Prod', models.CharField(max_length=100)),
                ('Source_Prod', models.CharField(blank=True, max_length=50)),
                ('Type_Pro', models.CharField(choices=[('ESPECE', 'Espèce'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECE', max_length=20)),
                ('Montant_Pro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Qte_Pro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Pourcentage_Pro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/Produits/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='clients.client')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-id'],
            },
        ),
    ]
