# Generated by Django 6.0.6 on 2026-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_paiementproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
