# Generated by Django 6.0.6 on 2026-08-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_alter_produit_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pourcentage',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
