# Generated by Django 6.0.6 on 2026-08-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_id'),
        ('produit', '0010_alter_produit_montant_alter_produit_pourcentage'),
        ('transentrant', '0009_alter_transentrant_adresse_alter_transentrant_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementproduit',
            options={'ordering': ['date', 'id'], 'verbose_name': 'Paiement produit', 'verbose_name_plural': 'Paiements produits'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='produit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/Produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='produit',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECE', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='transentrant.transentrant'),
        ),
    ]
