# Generated by Django 6.0.6 on 2026-09-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0001_initial'),
        ('users', '0009_alter_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='enregistreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes_enregistrees', to='users.appuser'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='type_virement',
            field=models.CharField(choices=[('Banque', 'Virement bancaire'), ('Cheque', 'Chèque'), ('Espece', 'Espèces'), ('Mobile', 'Mobile money')], max_length=100),
        ),
    ]
