# Generated by Django 6.0.6 on 2026-09-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0002_alter_recette_enregistreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
