# Generated by Django 6.0.6 on 2026-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_date_creation_appuser_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
    ]
