# Generated by Django 6.0.6 on 2026-08-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_personnel_created_at'),
        ('users', '0005_remove_appuser_categorieuser_appuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='personnel.personnel'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('Superviseur', 'Superviseur'), ('User', 'Utilisateur')], default='User', max_length=20),
        ),
    ]
