# Generated by Django 6.1.1 on 2026-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrateur'), ('ChauffeurEntreprise', 'Chauffeur Entreprise'), ('ChauffeurMica', 'Chauffeur Mica'), ('ChefMagasin', 'Chef Magasiné'), ('Magasin', 'Magasiné'), ('Superviseur', 'Superviseur'), ('UserMica', 'Comptable Mica'), ('UserEntreprise', 'Comptable Entreprise')], default='UserMica', max_length=50),
        ),
    ]
