"""
Django settings for transit_project project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path


# =====================================================
# BASE DIRECTORY
# =====================================================

BASE_DIR = Path(__file__).resolve().parent.parent



# =====================================================
# SECURITY
# =====================================================

SECRET_KEY = 'django-insecure-i*e$)74@sin4q+n!-&6w2^7g@((z2+#kaw*p$wy_9e3_9)hunc'

DEBUG = True

ALLOWED_HOSTS = []



# =====================================================
# APPLICATIONS
# =====================================================

INSTALLED_APPS = [

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',


    # Applications Transit ERP
    'clients',
    'avances',
    'personnel',
    'transentrant',
    'produit',
    'categorie',
    'users',
    'materiels',
    'materielsort',
    'materielEntre',
    'depense',
    'depot',
    'salaire',
    'audit',
    'retours',
    'logs',
]



# =====================================================
# MIDDLEWARE
# =====================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",


    # Authentification personnalisée ERP
    "users.middleware.LoginRequiredMiddleware",

]



# =====================================================
# URL / TEMPLATES
# =====================================================

ROOT_URLCONF = "transit_project.urls"


TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]


WSGI_APPLICATION = "transit_project.wsgi.application"



# =====================================================
# DATABASE
# =====================================================

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",

    }

}



# =====================================================
# PASSWORD VALIDATION
# =====================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },

]



# =====================================================
# LANGUAGE / TIME
# =====================================================

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Indian/Antananarivo"

USE_I18N = True

USE_TZ = True



# =====================================================
# FORMAT MONETAIRE
# =====================================================

USE_THOUSAND_SEPARATOR = True

THOUSAND_SEPARATOR = " "

DECIMAL_SEPARATOR = ","



# =====================================================
# STATIC FILES
# =====================================================

STATIC_URL = "/static/"


STATICFILES_DIRS = [

    BASE_DIR / "static",

]


STATIC_ROOT = BASE_DIR / "staticfiles"



# =====================================================
# MEDIA FILES
# =====================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"



# =====================================================
# AUTHENTIFICATION
# =====================================================

LOGIN_URL = "users:login"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "users:login"