# Generated by Django 6.0.6 on 2026-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiels',
            name='nombre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
