# Generated by Django 6.0.6 on 2026-07-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_materiels_unique_materiel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materiels',
            name='unique_materiel',
        ),
    ]
