# Generated by Django 6.0.6 on 2026-07-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_materiels_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiels',
            old_name='categorie',
            new_name='catMat',
        ),
        migrations.RenameField(
            model_name='materiels',
            old_name='type',
            new_name='typeMat',
        ),
    ]
