# Generated by Django 6.0.6 on 2026-07-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0003_rename_categorie_materiels_catmat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiels',
            name='nombre',
        ),
        migrations.AddField(
            model_name='materiels',
            name='stock_initial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
