# Generated by Django 6.0.6 on 2026-07-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0003_remove_materiels_unique_materiel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiels',
            options={'ordering': ['nom']},
        ),
    ]
