# Generated by Django 6.0.6 on 2026-07-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0004_alter_materiels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiels',
            options={},
        ),
        migrations.RemoveField(
            model_name='materiels',
            name='dateDepot',
        ),
    ]
