# Generated by Django 6.0.6 on 2026-07-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0004_remove_materiels_nombre_materiels_stock_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiels',
            options={'ordering': ['nom'], 'verbose_name': 'Matériel', 'verbose_name_plural': 'Matériels'},
        ),
    ]
