# Generated by Django 6.0.6 on 2026-07-05 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_remove_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banque', models.CharField(max_length=100)),
                ('numero_compte', models.CharField(max_length=50, unique=True)),
                ('titulaire', models.CharField(blank=True, max_length=150)),
                ('code_banque', models.CharField(blank=True, max_length=20)),
                ('agence', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift_bic', models.CharField(blank=True, max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='clients.client')),
            ],
            options={
                'ordering': ['nom_banque', 'numero_compte'],
            },
        ),
    ]
