# Generated by Django 6.0.6 on 2026-07-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=20)),
                ('categorie', models.CharField(choices=[('User', 'Client'), ('Admin', 'Administrateur'), ('SuperAdmin', 'SuperViseur')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/Personnel/')),
            ],
        ),
    ]
