# Generated by Django 6.0.6 on 2026-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='fonction',
            field=models.CharField(default='Employé', max_length=20),
        ),
    ]
