# Generated by Django 6.0.6 on 2026-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(default=0, upload_to='images/Personnel/'),
            preserve_default=False,
        ),
    ]
