# Generated by Django 6.0.6 on 2026-08-01 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='psalaire',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
