# Generated by Django 6.0.6 on 2026-08-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_alter_personnel_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='categorie',
            field=models.CharField(choices=[('Employe', 'Employé'), ('Employe', 'Employé'), ('Employe', 'Employé'), ('Chauffeur', 'Chauffeur'), ('Admin', 'Administrateur'), ('SuperAdmin', 'Superviseur')], default='Employe', max_length=20),
        ),
    ]
