# Generated by Django 6.0.6 on 2026-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_personnel_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/Personnel/'),
        ),
    ]
