# Generated by Django 6.0.6 on 2026-08-04 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_alter_personnel_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
