# Generated by Django 6.1.1 on 2026-09-30 19:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiaux', '0013_materiauxretour_receptionmateriau_and_more'),
        ('personnel', '0013_alter_personnel_typetravail'),
        ('users', '0011_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('budget_previsionnel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Budget prévisionnel')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets_enregistres', to='users.appuser', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du point')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Distance (km)')),
                ('travail_prevu', models.CharField(max_length=255, verbose_name='Travail prévu')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('actif', models.BooleanField(default=True, verbose_name='Point actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_responsables', to='personnel.personnel', verbose_name='Responsable')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Point de chantier',
                'verbose_name_plural': 'Points de chantier',
                'ordering': ['projet', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EquipeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(choices=[('INGENIEUR', 'Ingénieur Responsable du Chantier'), ('CHEF_CHANTIER', 'Chef de Chantier'), ('CHEF_MAGASIN', 'Chef Magasinier'), ('MAGASINIER', 'Magasinier'), ('CHAUFFEUR', 'Chauffeur'), ('OUVRIER', 'Ouvrier'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Fonction sur le projet')),
                ('date_debut', models.DateField(verbose_name="Début de l'affectation")),
                ('date_fin', models.DateField(verbose_name="Fin de l'affectation")),
                ('actif', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_projets', to='personnel.personnel', verbose_name='Personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipe', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Équipe de projet',
                'verbose_name_plural': 'Équipe des projets',
                'ordering': ['projet', 'fonction', 'personnel__nom'],
            },
        ),
        migrations.CreateModel(
            name='RapportMateriau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('point_ravitaillement', models.CharField(max_length=200, verbose_name='Point de ravitaillement')),
                ('date_ravitaillement', models.DateField(verbose_name='Date de ravitaillement')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_materiaux', to='personnel.personnel', verbose_name='Magasinier')),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_projets', to='materiaux.materiaux', verbose_name='Matériau')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_materiaux', to='projet.pointprojet', verbose_name='Point de chantier')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_materiaux', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Rapport matériau',
                'verbose_name_plural': 'Rapports matériaux',
                'ordering': ['-date_ravitaillement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RapportProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du rapport')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('avancement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Avancement (%)')),
                ('travaux_realises', models.TextField(blank=True, verbose_name='Travaux réalisés')),
                ('difficultes', models.TextField(blank=True, verbose_name='Difficultés rencontrées')),
                ('actions_planifiees', models.TextField(blank=True, verbose_name="Plan d'action")),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_projet', to='personnel.personnel', verbose_name='Auteur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_projet', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Rapport de projet',
                'verbose_name_plural': 'Rapports de projet',
                'ordering': ['-date_rapport', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RapportTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du travail')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projets/travaux/', verbose_name='Photo')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_travaux', to='personnel.personnel', verbose_name='Chef de chantier')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rapports_travaux', to='projet.pointprojet', verbose_name='Point de chantier')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_travaux', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Rapport de travail',
                'verbose_name_plural': 'Rapports de travaux',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RapportVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('kilometrage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage')),
                ('etat', models.CharField(max_length=100, verbose_name='État')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projets/vehicules/', verbose_name='Photo')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_vehicules', to='personnel.personnel', verbose_name='Chauffeur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_vehicules', to='projet.projet', verbose_name='Projet')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_projets', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Rapport véhicule',
                'verbose_name_plural': 'Rapports véhicules',
                'ordering': ['-date_rapport', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pointprojet',
            constraint=models.UniqueConstraint(fields=('projet', 'code'), name='unique_code_point_projet'),
        ),
        migrations.AddConstraint(
            model_name='equipeprojet',
            constraint=models.UniqueConstraint(fields=('projet', 'personnel'), name='unique_personnel_projet'),
        ),
    ]
