# Generated by Django 6.1.1 on 2026-10-03 01:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0014_activitetransport_point_projet_and_more'),
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name="Début de l'affectation")),
                ('date_fin', models.DateField(verbose_name="Fin de l'affectation")),
                ('kilometrage_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage initial')),
                ('kilometrage_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage final')),
                ('consommation_km_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Consommation (km/l)')),
                ('actif', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_vehicules_projets', to='personnel.personnel', verbose_name='Chauffeur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules_projet', to='projet.projet', verbose_name='Projet')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_projets', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Véhicule affecté au projet',
                'verbose_name_plural': 'Véhicules affectés aux projets',
                'ordering': ['-date_debut', '-id'],
                'constraints': [models.UniqueConstraint(fields=('projet', 'vehicule'), name='unique_vehicule_projet')],
            },
        ),
    ]
