# Generated by Django 6.1.1 on 2026-10-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_vehiculeprojet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculeprojet',
            name='vehicule',
            field=models.CharField(max_length=150, verbose_name='Véhicule'),
        ),
    ]
