# Generated by Django 6.1.1 on 2026-10-03 07:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0014_activitetransport_point_projet_and_more'),
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0003_alter_vehiculeprojet_vehicule'),
        ('users', '0012_alter_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipeprojet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pointprojet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rapportmateriau',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rapportprojet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rapporttravail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rapportvehicule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rapporttravail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projets/travaux/', verbose_name='Photo du travail'),
        ),
        migrations.CreateModel(
            name='ActiviteTransportProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transport', models.CharField(choices=[('MATERIAUX', 'Matériaux'), ('MATERIEL', 'Matériel'), ('PERSONNEL', 'Personnel'), ('MATERIAUX_MATERIEL', 'Matériaux + Matériel'), ('AUTRE', 'Autre')], default='MATERIAUX', max_length=30, verbose_name='Type de transport')),
                ('mission', models.CharField(max_length=255, verbose_name='Mission')),
                ('lieu_depart', models.CharField(max_length=255, verbose_name='Lieu de départ')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Distance (km)')),
                ('kilometrage_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage initial')),
                ('kilometrage_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage final')),
                ('consommation_km_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Consommation (km/L)')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantité transportée')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('date_transport', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date du transport')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport_projet', to='personnel.personnel', verbose_name='Chauffeur')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport_projet_enregistrees', to='users.appuser', verbose_name='Enregistré par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport_projet', to='projet.projet', verbose_name='Projet')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport_projet', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Activité transport du projet',
                'verbose_name_plural': 'Activités transport du projet',
                'ordering': ['-date_transport', '-id'],
            },
        ),
    ]
