# Generated by Django 6.1.1 on 2026-10-03
#
# La migration 0005 a déjà effectué la conversion physique
# de vehicule (texte) vers vehicule_id (ForeignKey).
#
# Cette migration met uniquement à jour l'état historique
# de Django sans modifier la structure SQLite.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materiaux",
            "0014_activitetransport_point_projet_and_more",
        ),
        (
            "projet",
            "0005_convert_vehiculeprojet_vehicule",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="vehiculeprojet",
                    name="vehicule",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations_projets",
                        to="materiaux.vehicule",
                        verbose_name="Véhicule",
                    ),
                ),
            ],
        ),
    ]