# Generated by Django 6.1.1 on 2026-10-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_alter_vehiculeprojet_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointprojet',
            name='responsable',
        ),
    ]
