# Generated by Django 6.1.1 on 2026-10-06 11:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0014_activitetransport_point_projet_and_more'),
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0009_vehiculeloursprojet_alter_pointprojet_options_and_more'),
        ('users', '0012_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceEquipeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Montant de l'avance")),
                ('date_avance', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'avance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_equipe_enregistrees', to='users.appuser', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': "Avance d'équipe",
                'verbose_name_plural': "Avances d'équipe",
                'ordering': ['-date_avance', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant du travail')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipages_projet_enregistres', to='users.appuser', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Équipage du projet',
                'verbose_name_plural': 'Équipages du projet',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipeMateriauProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Prix unitaire')),
                ('date_debut', models.DateTimeField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiaux_equipe_enregistres', to='users.appuser', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': "Matériau de l'équipe",
                'verbose_name_plural': 'Matériaux des équipes',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelExecutionProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_class', models.CharField(choices=[('INGENIEUR', 'Ingénieur Responsable de Projet'), ('CHEF_CHANTIER', 'Chef de Chantier'), ('CHEF_EQUIPE', "Chef d'équipe"), ('CHAUFFEUR_ENGIN', "Conducteur d'engin"), ('CHAUFFEUR', 'Chauffeur'), ('CHEF_MAGASIN', 'Chef Magasinier'), ('MAGASIN', 'Magasinier'), ('MINIER', 'Mpamaky vato'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Classe')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('type_contrat', models.CharField(choices=[('MENSUEL', 'Salarié mensuel'), ('FORFAITAIRE', 'Forfaitaire'), ('PRE_PAYER', 'Pré-payé')], default='MENSUEL', max_length=20, verbose_name='Type de contrat')),
                ('salaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salaire / Montant')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/EquipeExecution/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels_execution_enregistres', to='users.appuser', verbose_name='Enregistré par')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions_projets', to='personnel.personnel', verbose_name='Personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnels_execution', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': "Personnel d'exécution",
                'verbose_name_plural': "Personnel d'exécution",
                'ordering': ['date_debut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='VehiculeLourdsProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, verbose_name='Numéro matricule')),
                ('conducteur', models.CharField(max_length=255, verbose_name='Nom du conducteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules_lourds', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Véhicule lourd du projet',
                'verbose_name_plural': 'Véhicules lourds du projet',
                'ordering': ['matricule'],
            },
        ),
        migrations.DeleteModel(
            name='VehiculeLoursProjet',
        ),
        migrations.AlterModelOptions(
            name='vehiculeprojet',
            options={'ordering': ['-date_debut', '-id'], 'verbose_name': 'Véhicule / Engin affecté au projet', 'verbose_name_plural': 'Véhicules / Engins affectés aux projets'},
        ),
        migrations.AddField(
            model_name='vehiculeprojet',
            name='consommation_heure_litre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Consommation (L/h)'),
        ),
        migrations.AddField(
            model_name='vehiculeprojet',
            name='heures_finales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Heures finales'),
        ),
        migrations.AddField(
            model_name='vehiculeprojet',
            name='heures_initiales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Heures initiales'),
        ),
        migrations.AddField(
            model_name='vehiculeprojet',
            name='type_vehicule',
            field=models.CharField(choices=[('ROUTIER', 'Véhicule routier'), ('ENGIN', 'Engin de chantier')], default='ROUTIER', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pointprojet',
            name='localisation',
            field=models.CharField(blank=True, max_length=250, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='vehiculeprojet',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_vehicules_projets', to='personnel.personnel', verbose_name='Conducteur / Chauffeur'),
        ),
        migrations.AlterField(
            model_name='vehiculeprojet',
            name='consommation_km_litre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Consommation (km/L)'),
        ),
        migrations.AlterField(
            model_name='vehiculeprojet',
            name='vehicule',
            field=models.CharField(max_length=30, verbose_name='Véhicule / Engin'),
        ),
        migrations.AddField(
            model_name='equipageprojet',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipages', to='projet.pointprojet', verbose_name='Point de chantier'),
        ),
        migrations.AddField(
            model_name='equipemateriauprojet',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiaux_equipe', to='projet.pointprojet', verbose_name='Point de chantier'),
        ),
        migrations.AddField(
            model_name='equipemateriauprojet',
            name='typemateriaux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes_projet', to='materiaux.materiaux', verbose_name='Type de matériau'),
        ),
        migrations.AddField(
            model_name='equipemateriauprojet',
            name='personnel_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiaux_utilises', to='projet.personnelexecutionprojet', verbose_name='Travailleur'),
        ),
        migrations.AddField(
            model_name='equipageprojet',
            name='personnel_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipages', to='projet.personnelexecutionprojet', verbose_name="Personnel d'exécution"),
        ),
        migrations.AddField(
            model_name='avanceequipeprojet',
            name='personnel_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances', to='projet.personnelexecutionprojet', verbose_name='Travailleur'),
        ),
    ]
