# Generated by Django 6.1.1 on 2026-10-06 12:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0010_avanceequipeprojet_equipageprojet_and_more'),
        ('users', '0012_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementPersonnelProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('activite', models.CharField(max_length=255, verbose_name='Activité')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_personnel_enregistres', to='users.appuser', verbose_name='Enregistré par')),
                ('personnel_execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='projet.personnelexecutionprojet', verbose_name='Personnel')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_personnel', to='projet.pointprojet', verbose_name='Point de chantier')),
            ],
            options={
                'verbose_name': 'Mouvement du personnel',
                'verbose_name_plural': 'Mouvements du personnel',
                'ordering': ['-date_mouvement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MouvementVehiculeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('kilometrage_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage initial')),
                ('kilometrage_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage final')),
                ('heures_initiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Heures initiales')),
                ('heures_finales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Heures finales')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_vehicules_enregistres', to='users.appuser', verbose_name='Enregistré par')),
                ('point_arrivee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_vehicules_arrivee', to='projet.pointprojet', verbose_name="Point d'arrivée")),
                ('point_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_vehicules_depart', to='projet.pointprojet', verbose_name='Point de départ')),
                ('vehicule_projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='projet.vehiculeprojet', verbose_name='Véhicule / Engin')),
            ],
            options={
                'verbose_name': 'Mouvement véhicule',
                'verbose_name_plural': 'Mouvements véhicules',
                'ordering': ['-date_mouvement', '-id'],
            },
        ),
    ]
