# Generated by Django 6.1.1 on 2026-10-06 12:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0011_mouvementpersonnelprojet_mouvementvehiculeprojet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipeprojet',
            options={'ordering': ['projet', 'fonction'], 'verbose_name': 'Équipe de projet', 'verbose_name_plural': 'Équipe des projets'},
        ),
        migrations.AlterModelOptions(
            name='vehiculelourdsprojet',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='equipeprojet',
            name='unique_personnel_projet',
        ),
        migrations.AddField(
            model_name='equipeprojet',
            name='personnel_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_equipe', to='projet.personnelexecutionprojet', verbose_name="Personnel d'exécution du projet"),
        ),
        migrations.AddField(
            model_name='vehiculelourdsprojet',
            name='type_engin',
            field=models.CharField(blank=True, choices=[('PELLE', 'Pelle hydraulique'), ('BULLDOZER', 'Bulldozer'), ('CHARGEUSE', 'Chargeuse'), ('COMPACTEUR', 'Compacteur'), ('GRUE', 'Grue'), ('TRACTOPELLE', 'Tractopelle'), ('NIVELEUSE', 'Niveleuse'), ('AUTRE', 'Autre')], max_length=30, null=True, verbose_name="Type d'engin"),
        ),
        migrations.AlterField(
            model_name='equipageprojet',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='equipageprojet',
            name='personnel_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipages', to='projet.personnelexecutionprojet', verbose_name="Chef d'équipe"),
        ),
        migrations.AlterField(
            model_name='equipeprojet',
            name='fonction',
            field=models.CharField(choices=[('INGENIEUR', 'Ingénieur Responsable du Chantier'), ('CHEF_CHANTIER', 'Chef de Chantier'), ('CHEF_MAGASIN', 'Chef Magasinier'), ('MAGASINIER', 'Magasinier'), ('CHAUFFEUR', 'Chauffeur'), ('OUVRIER', 'Ouvrier'), ('CHEF_EQUIPE', "Chef d'équipe"), ('MINIER', 'Minier'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Fonction sur le projet'),
        ),
        migrations.AlterField(
            model_name='equipeprojet',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_projets', to='personnel.personnel', verbose_name="Personnel de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions_projets', to='personnel.personnel', verbose_name="Personnel de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salaire / Montant du contrat'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='type_class',
            field=models.CharField(choices=[('INGENIEUR', 'Ingénieur Responsable de Projet'), ('CHEF_CHANTIER', 'Chef de Chantier'), ('CHEF_EQUIPE', "Chef d'équipe"), ('CHAUFFEUR_ENGIN', "Conducteur d'engin"), ('CHAUFFEUR', 'Chauffeur'), ('CHEF_MAGASIN', 'Chef Magasinier'), ('MAGASIN', 'Magasinier'), ('MINIER', 'Minier / Mpamaky vato'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='type_contrat',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('FORFAITAIRE', 'Forfaitaire'), ('PRE_PAYER', 'Pré-payé')], default='MENSUEL', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='vehiculelourdsprojet',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engins_conduits', to='projet.personnelexecutionprojet', verbose_name='Conducteur'),
        ),
    ]
