# Generated by Django 6.1.2 on 2026-10-08 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0014_activitetransport_point_projet_and_more'),
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0012_alter_equipeprojet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelexecutionprojet',
            options={'ordering': ['projet', 'type_class', 'nom', 'personnel'], 'verbose_name': "Personnel d'exécution du projet", 'verbose_name_plural': "Personnels d'exécution des projets"},
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='point_projet',
            field=models.ForeignKey(blank=True, help_text="Obligatoire pour un Chef d'équipe.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnels_execution', to='projet.pointprojet', verbose_name='Point du projet'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnels_execution_enregistres', to='personnel.personnel', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='nom',
            field=models.CharField(blank=True, help_text="Nom de la personne externe au personnel de l'entreprise.", max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='personnel',
            field=models.ForeignKey(blank=True, help_text="Obligatoire pour les personnels de l'entreprise (Ingénieur, Chef de chantier, Chauffeur, etc.).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions_projets', to='personnel.personnel', verbose_name='Personnel'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnels_execution/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire / Montant'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='type_class',
            field=models.CharField(choices=[('INGENIEUR', 'Ingénieur'), ('CHEF_CHANTIER', 'Chef de chantier'), ('CHEF_EQUIPE', "Chef d'équipe"), ('CHAUFFEUR_ENGIN', "Chauffeur d'engin"), ('CHAUFFEUR', 'Chauffeur'), ('CHEF_MAGASIN', 'Chef magasin'), ('MAGASIN', 'Magasinier'), ('MINIER', 'Minier'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='type_contrat',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('FORFAITAIRE', 'Forfaitaire'), ('PRE_PAYER', 'Pré-payé')], max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.CreateModel(
            name='MateriauProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prevue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Quantité prévue')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='materiaux.materiaux', verbose_name='Matériau')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiaux_projet', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Matériau du projet',
                'verbose_name_plural': 'Matériaux du projet',
                'ordering': ['projet', 'materiau'],
            },
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='materiau_projet',
            field=models.ForeignKey(blank=True, help_text='Obligatoire pour un Minier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='miniers', to='projet.materiauprojet', verbose_name='Matériau du projet'),
        ),
        migrations.AddConstraint(
            model_name='materiauprojet',
            constraint=models.UniqueConstraint(fields=('projet', 'materiau'), name='unique_materiau_projet'),
        ),
    ]
