# Generated by Django 6.1.2 on 2026-10-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0013_alter_personnelexecutionprojet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelexecutionprojet',
            name='type_contrat',
        ),
    ]
