# Generated by Django 6.1.2 on 2026-10-08 05:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0014_remove_personnelexecutionprojet_type_contrat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnelexecutionprojet',
            options={'ordering': ['-date_debut', '-date_production', 'nom'], 'verbose_name': "Personnel d'exécution du projet", 'verbose_name_plural': "Personnels d'exécution des projets"},
        ),
        migrations.RemoveField(
            model_name='personnelexecutionprojet',
            name='salaire',
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='date_production',
            field=models.DateField(blank=True, null=True, verbose_name='Date de production'),
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='personnelexecutionprojet',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='materiau_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='miniers', to='projet.materiauprojet', verbose_name='Matériau du projet'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions_projets', to='personnel.personnel', verbose_name='Personnel'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='point_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personnels_execution', to='projet.pointprojet', verbose_name='Point du projet'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='type_class',
            field=models.CharField(choices=[('CHEF_EQUIPE', "Chef d'équipe"), ('CHAUFFEUR_ENGIN', "Chauffeur d'engin"), ('MINIER', 'Minier'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='personnelexecutionprojet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
