# Generated by Django 6.1.2 on 2026-10-08 18:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0017_alter_materiauprojet_materiau'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnginProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engin', models.CharField(max_length=30, verbose_name='Engin')),
                ('date_debut', models.DateField(verbose_name="Début de l'affectation")),
                ('date_fin', models.DateField(verbose_name="Fin de l'affectation")),
                ('heures_initiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Heures initiales')),
                ('heures_finales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Heures finales')),
                ('consommation_heure_litre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Consommation (L/h)')),
                ('actif', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_engins_projets', to='personnel.personnel', verbose_name='Conducteur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engins_projet', to='projet.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Engin affecté au projet',
                'verbose_name_plural': 'Engins affectés aux projets',
                'ordering': ['-date_debut', '-id'],
                'constraints': [models.UniqueConstraint(fields=('projet', 'engin'), name='unique_engin_projet')],
            },
        ),
    ]
