# Generated by Django 6.1.2 on 2026-10-09 11:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0018_enginprojet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementvehiculeprojet',
            options={'ordering': ['-date_mouvement', '-id'], 'verbose_name': 'Mouvement véhicule / engin', 'verbose_name_plural': 'Mouvements véhicules / engins'},
        ),
        migrations.AddField(
            model_name='mouvementvehiculeprojet',
            name='carburant_litre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Carburant consommé (litres)'),
        ),
        migrations.AddField(
            model_name='mouvementvehiculeprojet',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AddField(
            model_name='mouvementvehiculeprojet',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
        migrations.AlterField(
            model_name='mouvementvehiculeprojet',
            name='heures_finales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Compteur horaire final'),
        ),
        migrations.AlterField(
            model_name='mouvementvehiculeprojet',
            name='heures_initiales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Compteur horaire initial'),
        ),
        migrations.AlterField(
            model_name='mouvementvehiculeprojet',
            name='kilometrage_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage final (km)'),
        ),
        migrations.AlterField(
            model_name='mouvementvehiculeprojet',
            name='kilometrage_initial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kilométrage initial (km)'),
        ),
        migrations.AlterField(
            model_name='mouvementvehiculeprojet',
            name='point_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_vehicules_arrivee', to='projet.pointprojet', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='mouvementvehiculeprojet',
            name='point_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_vehicules_depart', to='projet.pointprojet', verbose_name='Lieu de départ'),
        ),
    ]
