# Generated by Django 5.2.14 on 2026-07-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0002_alter_avance_typeav'),
        ('personnel', '0003_alter_personnel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='id_client',
        ),
        migrations.AddField(
            model_name='avance',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='personnel.personnel'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
