# Generated by Django 6.0.6 on 2026-09-03 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0010_avance_dateenregistremeny_alter_avance_dateav'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='montant_recupere',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='avance',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
