# Generated by Django 6.0.6 on 2026-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='typeAv',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECE', max_length=20),
        ),
    ]
