# Generated by Django 6.0.6 on 2026-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0003_remove_avance_id_client_avance_personnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
