# Generated by Django 6.0.6 on 2026-08-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0004_alter_avance_id'),
        ('clients', '0009_alter_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='avance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='avance',
            name='montantAv',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
