# Generated by Django 6.0.6 on 2026-08-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0008_avance_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='client',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='vehicule',
        ),
    ]
