# Generated by Django 6.0.6 on 2026-09-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avances', '0011_avance_montant_recupere_avance_reste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avance',
            name='dateAv',
            field=models.DateField(),
        ),
    ]
