# Generated by Django 6.0.6 on 2026-08-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_appuser_email_alter_appuser_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_vehicule', models.CharField(max_length=8, verbose_name='Numéro véhicule')),
                ('piece_acheter', models.CharField(max_length=150, verbose_name='Pièce achetée')),
                ('nombre', models.PositiveIntegerField(default=1, verbose_name='Nombre')),
                ('prix_du_piece', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de la pièce')),
                ('date_cree', models.DateField(auto_now_add=True, verbose_name='Date création')),
                ('enregistrer_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entretiens', to='users.appuser', verbose_name='Enregistré par')),
            ],
        ),
    ]
