# Generated by Django 6.0.6 on 2026-07-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0001_initial'),
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='depot',
        ),
        migrations.AddField(
            model_name='depense',
            name='distribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='depot.distribution'),
            preserve_default=False,
        ),
    ]
