# Generated by Django 6.0.6 on 2026-08-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0003_depense_enregistre_par'),
        ('users', '0005_remove_appuser_categorieuser_appuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to='users.appuser'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
