# Generated by Django 6.0.6 on 2026-08-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0004_alter_depense_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={},
        ),
    ]
