# Generated by Django 6.0.6 on 2026-08-01 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0005_alter_depense_options'),
        ('depot', '0002_alter_depot_montantg_alter_distribution_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depense',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='depot.distribution'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
