# Generated by Django 6.0.6 on 2026-08-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0007_alter_depense_description_alter_depense_montant'),
        ('depot', '0002_alter_depot_montantg_alter_distribution_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='depot.distribution'),
        ),
    ]
