# Generated by Django 6.0.6 on 2026-08-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0002_depense_depot'),
        ('depense', '0008_alter_depense_distribution'),
    ]

    operations = [
    ]
