# Generated by Django 6.0.6 on 2026-08-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0009_merge_20260805_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.RemoveField(
            model_name='depense',
            name='depot',
        ),
    ]
