# Generated by Django 6.1.1 on 2026-09-18 00:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0001_initial'),
        ('users', '0010_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Docker',
                'verbose_name_plural': 'Dockers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True, verbose_name='Immatriculation')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('kilometrage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Kilométrage')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activite', models.DateField(verbose_name='Date')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('lieu_chargement', models.CharField(blank=True, max_length=150, verbose_name='Lieu de chargement')),
                ('destination', models.CharField(blank=True, max_length=150, verbose_name='Destination')),
                ('montant_transport', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant transport')),
                ('conducteur', models.CharField(blank=True, max_length=100, verbose_name='Conducteur')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='users.appuser', verbose_name='Enregistreur')),
                ('materiau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='materiaux.materiaux', verbose_name='Matériau')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Activité de transport',
                'verbose_name_plural': 'Activités de transport',
                'ordering': ['-date_activite', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaiementDocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('observation', models.CharField(blank=True, max_length=255, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_dockers', to='materiaux.activitetransport', verbose_name='Activité')),
                ('docker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='materiaux.docker', verbose_name='Docker')),
                ('enregistreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_dockers', to='users.appuser', verbose_name='Enregistreur')),
            ],
            options={
                'verbose_name': 'Paiement docker',
                'verbose_name_plural': 'Paiements dockers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReparationVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reparation', models.DateField(verbose_name='Date')),
                ('type_reparation', models.CharField(choices=[('REPARATION', 'Réparation'), ('ENTRETIEN', 'Entretien'), ('PNEU', 'Pneumatique'), ('PIECE', 'Pièce détachée'), ('MAIN_OEUVRE', "Main-d'œuvre"), ('AUTRE', 'Autre')], default='REPARATION', max_length=30, verbose_name='Type')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix unitaire')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total')),
                ('garage', models.CharField(blank=True, max_length=150, verbose_name='Garage / Fournisseur')),
                ('kilometrage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kilométrage')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparations', to='materiaux.activitetransport', verbose_name='Activité')),
                ('enregistreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparations_vehicules', to='users.appuser', verbose_name='Enregistreur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparations', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Réparation véhicule',
                'verbose_name_plural': 'Réparations véhicules',
                'ordering': ['-date_reparation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepenseGasoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gasoil', models.DateField(verbose_name='Date')),
                ('quantite_litre', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité (litres)')),
                ('prix_litre', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix par litre')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total')),
                ('station', models.CharField(blank=True, max_length=150, verbose_name='Station / Localisation')),
                ('kilometrage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kilométrage')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gasoil', to='materiaux.activitetransport', verbose_name='Activité de transport')),
                ('enregistreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gasoil', to='users.appuser', verbose_name='Enregistreur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gasoil', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dépense gasoil',
                'verbose_name_plural': 'Dépenses gasoil',
                'ordering': ['-date_gasoil', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(verbose_name='Date')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix unitaire')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant')),
                ('localisation', models.CharField(blank=True, max_length=150, verbose_name='Localisation')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='materiaux.activitetransport', verbose_name='Activité de transport')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='materiaux.categoriedepense', verbose_name='Catégorie')),
                ('enregistreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_materiaux', to='users.appuser', verbose_name='Enregistreur')),
                ('materiau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='materiaux.materiaux', verbose_name='Matériau')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='materiaux.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-id'],
            },
        ),
    ]
