# Generated by Django 6.1.1 on 2026-09-21 07:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0002_categoriedepense_docker_vehicule_activitetransport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementdocker',
            name='docker',
        ),
        migrations.RenameField(
            model_name='activitetransport',
            old_name='lieu_chargement',
            new_name='lieu_depart',
        ),
        migrations.RemoveField(
            model_name='activitetransport',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='depensegasoil',
            name='activite',
        ),
        migrations.RemoveField(
            model_name='depensegasoil',
            name='kilometrage',
        ),
        migrations.RemoveField(
            model_name='depensegasoil',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='depensegasoil',
            name='station',
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='kilometrage',
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='observation',
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='designation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Désignation'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='Cout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name="Main d'œuvre du garagiste"),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='chauffeur',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='main_oeuvre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name="Main d'œuvre"),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='montant_main_oeuvre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name="Montant main d'œuvre"),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='num_auto_ancien',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Num Auto ancien'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='num_auto_nouveau',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Num Auto nouveau'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='piece_remplacante',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Pièce remplaçante'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='piece_remplacee',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Pièce remplacée'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='montant_transport',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Montant transport'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='garage',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Garage / Fournisseur'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix unitaire pièce'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total pièces'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='type_reparation',
            field=models.CharField(choices=[('REPARATION', 'Réparation'), ('CHANGEMENT', 'Changement')], default='REPARATION', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='unite',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unité'),
        ),
        migrations.DeleteModel(
            name='Docker',
        ),
    ]
