# Generated by Django 6.1.1 on 2026-09-21 08:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0003_remove_paiementdocker_docker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementdocker',
            options={'ordering': ['-date_creation', '-id'], 'verbose_name': 'Paiement docker', 'verbose_name_plural': 'Paiements dockers'},
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='activite',
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='main_oeuvre',
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='num_auto_ancien',
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='num_auto_nouveau',
        ),
        migrations.AlterField(
            model_name='paiementdocker',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_dockers', to='materiaux.activitetransport', verbose_name='Activité de transport'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='Cout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name="Main d'œuvre garagiste"),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='garage',
            field=models.CharField(blank=True, max_length=150, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='piece_remplacante',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pièce remplaçante'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='piece_remplacee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pièce remplacée'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Total pièce'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='type_reparation',
            field=models.CharField(choices=[('REPARATION', 'Réparation'), ('CHANGEMENT', 'Changement de pièce')], default='REPARATION', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='unite',
            field=models.CharField(blank=True, max_length=50, verbose_name='Unité'),
        ),
    ]
