# Generated by Django 6.1.1 on 2026-09-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0005_reparationvehicule_photo_piece_remplacante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='piece_remplacante',
        ),
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='piece_remplacee',
        ),
    ]
