# Generated by Django 6.1.1 on 2026-09-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0006_remove_reparationvehicule_piece_remplacante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='activite',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='materiau',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='unite',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='vehicule',
        ),
    ]
