# Generated by Django 6.1.1 on 2026-09-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0007_remove_depense_activite_remove_depense_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depensegasoil',
            name='prix_litre',
        ),
    ]
