# Generated by Django 6.1.1 on 2026-09-21 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0008_remove_depensegasoil_prix_litre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitetransport',
            options={'ordering': ['-date_activite', '-id'], 'verbose_name': 'Déplacement véhicule', 'verbose_name_plural': 'Déplacements véhicules'},
        ),
        migrations.RemoveField(
            model_name='activitetransport',
            name='materiau',
        ),
        migrations.RemoveField(
            model_name='activitetransport',
            name='montant_transport',
        ),
        migrations.RemoveField(
            model_name='activitetransport',
            name='observation',
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='mission',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='type_transport',
            field=models.CharField(choices=[('PERSONNEL', 'Personnel'), ('MATERIELS', 'Matériels'), ('MATERIAUX', 'Matériaux')], default='MATERIAUX', max_length=20, verbose_name='Personnel / Matériels / Matériaux'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='conducteur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='designation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='lieu_depart',
            field=models.CharField(blank=True, max_length=150, verbose_name='Départ'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='materiaux.vehicule', verbose_name='N° Auto'),
        ),
    ]
