# Generated by Django 6.1.1 on 2026-09-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0009_alter_activitetransport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitetransport',
            name='designation',
        ),
    ]
