# Generated by Django 6.1.1 on 2026-09-21 12:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0010_remove_activitetransport_designation'),
        ('users', '0011_alter_appuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitetransport',
            options={'ordering': ['-date_activite', '-id'], 'verbose_name': 'Activité de transport', 'verbose_name_plural': 'Activités de transport'},
        ),
        migrations.AlterModelOptions(
            name='materiauxentree',
            options={'ordering': ['-date_entree', '-id'], 'verbose_name': 'Entrée matériau', 'verbose_name_plural': 'Entrées matériaux'},
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='materiaux.categoriedepense', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='depense',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='materiaux.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='depensegasoil',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Prix / litre'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='conducteur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Conducteur'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='destination',
            field=models.CharField(blank=True, max_length=255, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport_enregistrees', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='lieu_depart',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lieu de départ'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='mission',
            field=models.CharField(max_length=255, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='type_transport',
            field=models.CharField(choices=[('PERSONNEL', 'Personnel'), ('MATERIELS', 'Matériels'), ('MATERIAUX', 'Matériaux')], default='MATERIAUX', max_length=20, verbose_name='Type de transport'),
        ),
        migrations.AlterField(
            model_name='activitetransport',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='materiaux.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AlterField(
            model_name='categoriedepense',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_materiaux', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='depensegasoil',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gasoil', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='depensegasoil',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='materiaux',
            name='libelle',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='materiaux',
            name='unite',
            field=models.CharField(max_length=50, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='materiauxdivision',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Destination / Magasin'),
        ),
        migrations.AlterField(
            model_name='materiauxdivision',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiaux_divisions', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='materiauxentree',
            name='destination',
            field=models.CharField(blank=True, max_length=255, verbose_name='Provenance'),
        ),
        migrations.AlterField(
            model_name='materiauxentree',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiaux_entrees', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='materiauxout',
            name='destination',
            field=models.CharField(blank=True, max_length=255, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='materiauxout',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties', to='materiaux.materiauxdivision', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='materiauxout',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiaux_sorties', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='paiementdocker',
            name='activite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_dockers', to='materiaux.activitetransport', verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='paiementdocker',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_dockers', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='paiementdocker',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='Cout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Coût historique'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='chauffeur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparations_vehicules', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='garage',
            field=models.CharField(blank=True, max_length=255, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='montant_main_oeuvre',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="Main d'œuvre"),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='photo_piece_remplacante',
            field=models.ImageField(blank=True, null=True, upload_to='reparations/pieces_remplacantes/', verbose_name='Photo pièce remplacée par'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='photo_piece_remplacee',
            field=models.ImageField(blank=True, null=True, upload_to='reparations/pieces_remplacees/', verbose_name='Photo pièce remplacée'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Total pièce historique'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='type_reparation',
            field=models.CharField(choices=[('REPARATION', 'Réparation'), ('CHANGEMENT', 'Changement')], default='REPARATION', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=50, unique=True, verbose_name='Immatriculation'),
        ),
    ]
