# Generated by Django 6.1.1 on 2026-09-21 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0011_alter_activitetransport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementdocker',
            name='date_activite',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
