# Generated by Django 6.1.1 on 2026-09-30 19:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0012_paiementdocker_date_activite'),
        ('personnel', '0013_alter_personnel_typetravail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriauxRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité retournée')),
                ('date_retour', models.DateField(verbose_name='Date du retour')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Retour matériau',
                'verbose_name_plural': 'Retours matériaux',
                'ordering': ['-date_retour', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionMateriau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité reçue')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réception de matériau',
                'verbose_name_plural': 'Réceptions de matériaux',
                'ordering': ['-date_reception', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationMateriau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité utilisée')),
                ('date_utilisation', models.DateField(verbose_name='Date')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilisation de matériau',
                'verbose_name_plural': 'Utilisations de matériaux',
                'ordering': ['-date_utilisation', '-id'],
            },
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='chauffeur_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='personnel.personnel', verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='kilometrage_arrivee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Km arrivée'),
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='kilometrage_depart',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Km départ'),
        ),
    ]
