# Generated by Django 6.1.1 on 2026-09-30 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaux', '0013_materiauxretour_receptionmateriau_and_more'),
        ('personnel', '0013_alter_personnel_typetravail'),
        ('projet', '0001_initial'),
        ('users', '0011_alter_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitetransport',
            name='point_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='projet.pointprojet', verbose_name='Point de chantier'),
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_transport', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='activitetransport',
            name='sortie_materiau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='materiaux.materiauxout', verbose_name='Sortie matériau'),
        ),
        migrations.AddField(
            model_name='depense',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='depensegasoil',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depenses_gasoil', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='materiauxout',
            name='point_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorties_materiaux', to='projet.pointprojet', verbose_name='Point de chantier'),
        ),
        migrations.AddField(
            model_name='materiauxout',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorties_materiaux', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='paiementdocker',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_dockers', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='chauffeur_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparations_vehicules', to='personnel.personnel', verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reparations_vehicules', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='materiauxretour',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_materiaux', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='materiauxretour',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='materiaux.materiauxout', verbose_name='Sortie magasin'),
        ),
        migrations.AddField(
            model_name='receptionmateriau',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_materiaux', to='projet.pointprojet', verbose_name='Point de chantier'),
        ),
        migrations.AddField(
            model_name='receptionmateriau',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_materiaux', to='projet.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='receptionmateriau',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_materiaux', to='personnel.personnel', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='receptionmateriau',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions_materiaux', to='materiaux.activitetransport', verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='materiauxretour',
            name='reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='materiaux.receptionmateriau', verbose_name='Réception chantier'),
        ),
        migrations.AddField(
            model_name='utilisationmateriau',
            name='enregistreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_materiaux', to='users.appuser', verbose_name='Enregistré par'),
        ),
        migrations.AddField(
            model_name='utilisationmateriau',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations', to='materiaux.receptionmateriau', verbose_name='Réception'),
        ),
    ]
