# Generated by Django 6.0.6 on 2026-07-04 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transentrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chauf_Ent', models.CharField(blank=True, max_length=100)),
                ('NumVeh_Ent', models.CharField(max_length=50)),
                ('NumPermis_Ent', models.CharField(max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='images/VehiculesEntrant/')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
