# Generated by Django 6.0.6 on 2026-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transentrant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transentrant',
            old_name='NumVeh_Ent',
            new_name='num_vehicule',
        ),
        migrations.RenameField(
            model_name='transentrant',
            old_name='NumPermis_Ent',
            new_name='permis',
        ),
        migrations.RemoveField(
            model_name='transentrant',
            name='Chauf_Ent',
        ),
        migrations.RemoveField(
            model_name='transentrant',
            name='adresse',
        ),
        migrations.AddField(
            model_name='transentrant',
            name='chauffeur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
