# Generated by Django 6.0.6 on 2026-08-01 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transentrant', '0004_alter_transentrant_num_vehicule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transentrant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transentrant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transentrants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='permis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='transentrant/'),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
