# Generated by Django 6.0.6 on 2026-08-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transentrant', '0005_transentrant_created_at_transentrant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transentrant',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
