# Generated by Django 6.0.6 on 2026-08-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transentrant', '0008_alter_transentrant_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transentrant',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/transentrants/'),
        ),
    ]
