# Generated by Django 6.0.6 on 2026-08-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transentrant', '0009_alter_transentrant_adresse_alter_transentrant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transentrant',
            name='cin',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='num_vehicule',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='transentrant',
            name='permis',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
