# Generated by Django 6.0.6 on 2026-07-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
