# Generated by Django 6.0.6 on 2026-07-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
    ]
