# Generated by Django 6.0.6 on 2026-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
