# Generated by Django 6.0.6 on 2026-09-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_id'),
        ('users', '0009_alter_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_enregistres', to='users.appuser'),
        ),
    ]
