# Generated by Django 6.0.6 on 2026-08-04 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_categorie_description_alter_categorie_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
