# Generated by Django 6.0.6 on 2026-07-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materielsort', '0003_rename_dateav_materielsort_datesortie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielEntre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nb_Entre', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dateEntre', models.DateTimeField(auto_now_add=True)),
                ('id_MaterielSort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materielsort.materielsort')),
            ],
        ),
    ]
