# Generated by Django 6.0.6 on 2026-07-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materielEntre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielentre',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
