# Generated by Django 6.0.6 on 2026-07-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materielEntre', '0001_initial'),
        ('materiels', '0005_alter_materiels_options'),
        ('materielsort', '0004_alter_materielsort_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materielentre',
            options={'ordering': ['-dateEntre'], 'verbose_name': 'Entrée de matériel', 'verbose_name_plural': 'Entrées de matériel'},
        ),
        migrations.AddField(
            model_name='materielentre',
            name='id_Materiel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='materiels.materiels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materielentre',
            name='id_MaterielSort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours', to='materielsort.materielsort'),
        ),
    ]
