# Generated by Django 6.0.6 on 2026-07-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materielEntre', '0005_alter_materielentre_options_and_more'),
        ('materielsort', '0002_alter_materielsort_id_materiel_delete_materiels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materielentre',
            name='materiel',
        ),
        migrations.AddField(
            model_name='materielentre',
            name='id_MaterielSort',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='materielsort.materielsort'),
            preserve_default=False,
        ),
    ]
