# Generated by Django 6.0.6 on 2026-09-04 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materielEntre', '0007_materielentre_responsable_entree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielentre',
            name='dateEnregistreur',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materielentre',
            name='dateEntre',
            field=models.DateField(),
        ),
    ]
