# Generated by Django 6.0.6 on 2026-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materielEntre', '0009_alter_materielentre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materielentre',
            name='dateEntre',
            field=models.DateField(),
        ),
    ]
