# Generated by Django 6.0.6 on 2026-08-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_appuser_email_alter_appuser_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('objet', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.appuser')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
