# Generated by Django 6.0.6 on 2026-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
