# Generated by Django 6.0.6 on 2026-08-06 15:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanceclient', '0001_initial'),
        ('users', '0006_alter_appuser_email_alter_appuser_personnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avanceclient',
            options={'ordering': ['date', 'id'], 'verbose_name': 'Avance client', 'verbose_name_plural': 'Avances clients'},
        ),
        migrations.RenameField(
            model_name='avanceclient',
            old_name='utilise',
            new_name='montant_retour',
        ),
        migrations.AddField(
            model_name='avanceclient',
            name='montant_utilise',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='avanceclient',
            name='enregistrer_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_client_enregistrees', to='users.appuser'),
        ),
    ]
