# Generated by Django 6.0.6 on 2026-09-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depensesoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depensesoc',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Dépense Soc', 'verbose_name_plural': 'Dépenses Soc'},
        ),
    ]
