# Generated by Django 6.0.6 on 2026-09-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depensesoc', '0002_alter_depensesoc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depensesoc',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
    ]
