# Generated by Django 5.2.14 on 2026-07-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_photo'),
        ('salaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='personnel.personnel'),
        ),
    ]
