# Generated by Django 5.2.14 on 2026-07-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0003_salaire_client_salaire_target_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='client',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='target_type',
        ),
    ]
