# Generated by Django 6.0.6 on 2026-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0005_salaire_enregistreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='date',
            field=models.DateField(),
        ),
    ]
