# Generated by Django 6.0.6 on 2026-08-01 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_categorie_description_alter_categorie_nom'),
        ('personnel', '0009_alter_personnel_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='categorie.categorie'),
        ),
    ]
