# Generated by Django 6.0.6 on 2026-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_personnel_fincontrat_personnel_lieutravail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='typeTravail',
            field=models.CharField(choices=[('Mica', 'Mica'), ('Construction', 'Construction')], default='Construction', max_length=30),
        ),
    ]
