# Generated by Django 5.2.14 on 2026-08-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculesortant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculesortant',
            name='remorque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculesortant',
            name='ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
