# Generated by Django 6.0.6 on 2026-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculesortant', '0002_alter_vehiculesortant_remorque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculesortant',
            name='montant_transport',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
