# Generated by Django 6.0.6 on 2026-08-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculesortant', '0003_vehiculesortant_montant_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculesortant',
            old_name='montant_transport',
            new_name='montant',
        ),
    ]
