# Generated by Django 6.0.6 on 2026-07-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0003_alter_personnel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantG', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposant', models.CharField(default='BANK', editable=False, max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='depot.depot')),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_recues', to='personnel.personnel')),
            ],
        ),
    ]
