# Generated by Django 5.2.14 on 2026-08-02 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
        ('personnel', '0003_alter_personnel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='part_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='part_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='personnel_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_personnel_1', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='depot',
            name='personnel_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_personnel_2', to='personnel.personnel'),
        ),
    ]
