# Generated by Django 6.0.6 on 2026-08-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_alter_depot_montantg_alter_distribution_montant'),
        ('depot', '0002_depot_part_1_depot_part_2_depot_personnel_1_and_more'),
    ]

    operations = [
    ]
