# Generated by Django 6.0.6 on 2026-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_merge_20260805_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='depot',
            name='nom',
            field=models.CharField(blank=True, default='Dépôt', max_length=150),
        ),
    ]
