# Generated by Django 6.0.6 on 2026-07-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiels', '0002_materiels_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_MatSort', models.CharField(max_length=255)),
                ('Nb_MatSort', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Obs_MatSort', models.TextField(max_length=255)),
                ('dateAv', models.DateTimeField(auto_now_add=True)),
                ('id_Materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.materiels', verbose_name='Matériel')),
            ],
        ),
    ]
