# Generated by Django 6.0.6 on 2026-07-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0004_remove_materiels_nombre_materiels_stock_initial'),
        ('materielsort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materielsort',
            name='Obs_MatSort',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materielsort',
            name='id_Materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiels.materiels'),
        ),
    ]
