# Generated by Django 6.0.6 on 2026-07-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0004_remove_materiels_nombre_materiels_stock_initial'),
        ('materielsort', '0002_alter_materielsort_obs_matsort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materielsort',
            old_name='dateAv',
            new_name='dateSortie',
        ),
        migrations.RemoveField(
            model_name='materielsort',
            name='Obs_MatSort',
        ),
        migrations.RemoveField(
            model_name='materielsort',
            name='Res_MatSort',
        ),
        migrations.AlterField(
            model_name='materielsort',
            name='id_Materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='materiels.materiels'),
        ),
    ]
