# Generated by Django 6.0.6 on 2026-07-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materielsort', '0003_rename_dateav_materielsort_datesortie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materielsort',
            options={'ordering': ['-dateSortie'], 'verbose_name': 'Sortie de matériel', 'verbose_name_plural': 'Sorties de matériel'},
        ),
    ]
