# Generated by Django 6.0.6 on 2026-07-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_telephone'),
        ('contactclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
